### ISSUE TITLE
zk plugin not showing up in IntelliJ 15.0.1

### ISSUE THREAD

**Issue by IndisRepair** [jumperchen/zkidea#11]
Installed plugin two different ways, accessing the plugin through IntelliJ and downloading ZK plugin then installing. It shows up as an active plugin but when I try to create a Maven project ZK does not show up.

**Comment by jumperchen** [comment]
It seems like the IntelliJ changes some plugin API, so the current version won't work with it.

**Comment by IndisRepair** [comment]
Do you have any idea when you will release a fixed version?

**Comment by jumperchen** [comment]
when? not sure, it needs some time to study their source code to see what happened.

**Comment by IndisRepair** [comment]
A week, a month, or …? Need to make a decision

 

Thanks for the reply

**Comment by jumperchen** [comment]
After re-verify again, ZK plugin can work with IntelliJ 15.0.1 version from this 0.1.6 version - https://plugins.jetbrains.com/plugin/7855
