### ISSUE TITLE
listitem not supporting events inherited from HtmlBasedComponent ?

### ISSUE THREAD

**Issue by rickcr** [jumperchen/zkidea#9]
I like to use onClick and onRightClick on listitem within my template, but as you can see in the image, they're not coming through as supported events?

![screen shot 2015-08-25 at 2 52 48 pm](https://cloud.githubusercontent.com/assets/23496/9476155/440477ac-4b39-11e5-8d2a-25e78296d0a2.png)

**Comment by jumperchen** [comment]
it's a zul.xsd issue which will be fixed from zk project.

**Comment by jumperchen** [comment]
It has been fixed here - https://github.com/zkoss/zk/commit/7d078fc53713528be959aaca11596f0f26e231b7

The ZK IntelliJ plugin will update it automatically in a week. Or you can delete the IntelliJ's caches folder, it may update it ASAP.
